repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --check-only .
        language: system
        types: [python]
        pass_filenames: false

      - id: django-tests
        name: tests
        entry: docker-compose run --rm web-app sh -c 'python manage.py test'
        language: system
        types: [python]
        pass_filenames: false
