services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./map_project:/service
    command: >
        sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=database
      - DB_USER=admin
      - DB_NAME=city_map
      - DB_PASSWORD=admin

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=city_map
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

