# Generated by Django 3.2.16 on 2024-06-30 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReportTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_status', models.CharField(choices=[('not_started', 'Не почато'), ('in_process', 'Проходить'), ('ended', 'Завершилось')], default='not_started', max_length=32)),
                ('event_age', models.CharField(choices=[('+0', '+0'), ('+6', '+6'), ('+12', '+12'), ('+16', '+16'), ('+18', '+18')], default='+0', max_length=4)),
                ('begin_day', models.DateField()),
                ('begin_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('address', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('coordinates', models.JSONField()),
                ('price', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('created_by_org', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnverifiedEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_revue', models.CharField(choices=[('aproved', 'Підтверджено'), ('not_aproved', 'Не підтверджено'), ('in_revue', 'На перевірці')], default='in_revue', max_length=64)),
                ('recieved', models.DateTimeField(auto_now_add=True)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unverifiedevents', to='events.events')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.eventtypes'),
        ),
        migrations.CreateModel(
            name='EventReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventreports', to='events.events')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventreports', to='events.eventreporttypes')),
            ],
        ),
        migrations.CreateModel(
            name='EventImgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='events')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventimgs', to='events.events')),
            ],
        ),
        migrations.CreateModel(
            name='EventGuests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventguests', to='events.events')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventguests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'guest')},
            },
        ),
    ]
