# Generated by Django 3.2.16 on 2024-06-30 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='event_guests',
            field=models.ManyToManyField(related_name='event_guests', through='events.EventGuests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='event_reports',
            field=models.ManyToManyField(related_name='event_reports', through='events.EventReports', to='events.EventReportTypes'),
        ),
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.eventtypes'),
        ),
        migrations.AddField(
            model_name='eventreports',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events'),
        ),
        migrations.AddField(
            model_name='eventreports',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventreporttypes'),
        ),
        migrations.AddField(
            model_name='eventimgs',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventimgs', to='events.events'),
        ),
        migrations.AddField(
            model_name='eventguests',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events'),
        ),
        migrations.AddField(
            model_name='eventguests',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='eventguests',
            unique_together={('event', 'guest')},
        ),
    ]
