# Generated by Django 3.2.16 on 2024-09-04 16:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventguests',
            unique_together={('event', 'guest')},
        ),
    ]
