# Generated by Django 3.2.16 on 2024-07-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventreports_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='result_revue',
            field=models.CharField(choices=[('Підтверджено', 'Підтверджено'), ('Відмова', 'Відмова'), ('На перевірці', 'На перевірці')], db_index=True, default='На перевірці', max_length=64, verbose_name='Статус перевірки'),
        ),
        migrations.AlterField(
            model_name='historicalevents',
            name='result_revue',
            field=models.CharField(choices=[('Підтверджено', 'Підтверджено'), ('Відмова', 'Відмова'), ('На перевірці', 'На перевірці')], db_index=True, default='На перевірці', max_length=64, verbose_name='Статус перевірки'),
        ),
    ]
