# Generated by Django 3.2.16 on 2024-07-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_unverifiedevents_result_revue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_age',
            field=models.CharField(choices=[('+0', '+0'), ('+6', '+6'), ('+12', '+12'), ('+16', '+16'), ('+18', '+18')], db_index=True, default='+0', max_length=4),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_status',
            field=models.CharField(choices=[('not_started', 'Не почато'), ('in_process', 'Проходить'), ('ended', 'Завершилось')], db_index=True, default='not_started', max_length=32),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['event_status', 'event_age'], name='events_even_event_s_0a67fc_idx'),
        ),
    ]
