# Generated by Django 3.2.16 on 2024-07-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20240717_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='result_revue',
            field=models.CharField(choices=[('approved', 'Підтверджено'), ('rejected', 'Відмова'), ('in_revue', 'На перевірці')], db_index=True, default='in_revue', max_length=64, verbose_name='Статус перевірки'),
        ),
        migrations.AlterField(
            model_name='historicalevents',
            name='result_revue',
            field=models.CharField(choices=[('approved', 'Підтверджено'), ('rejected', 'Відмова'), ('in_revue', 'На перевірці')], db_index=True, default='in_revue', max_length=64, verbose_name='Статус перевірки'),
        ),
    ]
