# Generated by Django 3.2.16 on 2024-07-02 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_auto_20240701_2000"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventStatusEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(max_length=64, verbose_name="Статус події"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventstatusemail",
                        to="events.events",
                        verbose_name="Подія",
                    ),
                ),
            ],
        ),
    ]
