# Generated by Django 3.2.16 on 2024-08-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievementsprogressstatus",
            name="is_achieved",
            field=models.BooleanField(default=False),
        ),
    ]
