# Generated by Django 3.2.16 on 2024-08-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_alter_achievementsprogressstatus_is_achieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='keyword',
            field=models.CharField(choices=[('DV', 'default_value'), ('UP', 'update_profile'), ('CE', 'create_event')], default='DV', max_length=128),
        ),
    ]
