# Generated by Django 3.2.16 on 2024-07-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_achievementsprogressstatus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementsprogressstatus',
            name='is_achieved',
            field=models.BooleanField(),
        ),
    ]
