# Generated by Django 3.2.16 on 2024-07-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_alter_achievementsprogressstatus_is_achieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementsprogressstatus',
            name='is_achieved',
            field=models.BooleanField(default=False),
        ),
    ]
