# Generated by Django 3.2.16 on 2024-09-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_achievements_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='keyword',
            field=models.CharField(choices=[('DV', 'default_value'), ('UP', 'update_profile'), ('CE', 'create_event'), ('CS', 'create_subscription')], default='DV', max_length=128),
        ),
    ]
