# Generated by Django 3.2.16 on 2024-08-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verif",
        ),
        migrations.DeleteModel(
            name="UserVerification",
        ),
    ]
