# Generated by Django 3.2.16 on 2024-07-01 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Електронна адреса'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Про себе'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='inst_link',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='Instagram посилання'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='users/profile_picture/', verbose_name='Фото користувача'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='want_newsletters',
            field=models.BooleanField(default=False, verbose_name='Згоден отримувати новини'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='expired_at',
            field=models.DateTimeField(verbose_name='Дійсний до'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='verif_to',
            field=models.DateTimeField(verbose_name='Активовано до'),
        ),
    ]
