# Generated by Django 3.2.16 on 2024-09-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'subscribe_to'], name='users_users_user_id_0108fe_idx'),
        ),
    ]
