# Generated by Django 3.2.16 on 2024-07-01 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240701_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Користувача', 'verbose_name_plural': 'Користувачі'},
        ),
        migrations.AlterModelOptions(
            name='userlevel',
            options={'verbose_name': 'Тип рівня користувача', 'verbose_name_plural': 'Рівні користувачів'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_org',
            field=models.BooleanField(default=False, verbose_name='Зареєстрований як організація'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verif',
            field=models.BooleanField(default=False, verbose_name='Верифікований'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='users.userlevel', verbose_name='Рівень користувача'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
