# Generated by Django 3.2.16 on 2024-07-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240701_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_org',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Зареєстрований як організація'),
        ),
    ]
