# Generated by Django 3.2.16 on 2024-07-10 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240710_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userlevel', verbose_name='Рівень користувача'),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_subscriptions', to='users.userprofile'),
        ),
    ]
