# Generated by Django 3.2.16 on 2024-06-28 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('about_us', models.CharField(max_length=512)),
                ('org_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.orgtypes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('website', 'Website'), ('other', 'Other')], default='other', max_length=20)),
                ('link', models.URLField(max_length=256)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationlinks', to='organizations.organizations')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationImgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='org/')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationimgs', to='organizations.organizations')),
            ],
        ),
    ]
